spring.application.name=KeyStoreUtil

### NOTE:- Current using PKCE type keystore only[ not keystore.jks or  keystore.cer], mentioned below###  \keys\keystore.p12
app.jwt.keyStorePKCE12-location=classpath:keys\\keystore.p12
app.jwt.keypairPKCE12-alias=signjwt
app.jwt.keyStorePKCE12-password=abhimanyu
app.jwt.keyStorePKCE12.deststore-password=abhimanyu
app.jwt.keyStorePKCE12.destkey-password=abhimanyu
app.jwt.keyStorePKCE12.storetype=PKCS12
### Current using PKCE type keystore only, mentioned Above###
### KeyStore End ####